# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

steps:
  - command: ci/chaos/chaos.sh
    branches: master
    timeout_in_minutes: 300
    artifact_paths: target/chaos.log
    plugins:
      - MaterializeInc/uid#master: ~
      - docker-compose#v3.0.3:
          config: ci/slt/docker-compose.yml
          run: sqllogictest
